### ISSUE TITLE
Code release timeline

### ISSUE THREAD

**Issue by zmurez** [google-research/magvit#2]
Any estimate what "very shortly" means? Looking forward to it. Thanks!

**Comment by 20141888** [comment]
Since when does the 'short' mean longer than 4 months??

**Comment by JosephThePatrician** [comment]
There is an implementation of this model [here](https://github.com/RyuGood0/MAGVIT-pytorch), but I don't know if its good though. Maybe somebody have tried it? If you get any results with it, please let us know

**Comment by Lijun-Yu** [comment]
I hate the delay in the code release due to company review policies... but hopefully it will be out this week during CVPR. 

The initial version will live at https://github.com/google-research/magvit (not yet online as of 06/19). We are also going to release model weights trained on non-proprietary datasets, along with generated samples, so long as they're approved.

I'm also happy to help with any potential Pytorch reimplementations.

**Comment by mehdizade** [comment]
Hi Lijun-Yu

Is there any update on the timeline for publishing the code for the MAGVIT?

**Comment by xiaobuding888** [comment]
will the code be available this month?

**Comment by yueyang130** [comment]
Hi, could you please release the training code and also pretrained models?

**Comment by yueyang130** [comment]
Any torch version code would be released?

**Comment by Lijun-Yu** [comment]
Hi all! Good news, our code release has been finally approved. The code will be online on Monday.
Pretrained weights for these generative models face some extra reviews, but we'll try to release them as soon as possible.

**Comment by roadjiang** [comment]
The official code release will be next week under a different GitHub path that is managed by Google.

**Comment by Lijun-Yu** [comment]
Training and inference code are now online!

**Comment by XinyangHan** [comment]
Really awesome work! May I ask if there is an estimation for the release of checkpoints?
